<a href="https://colab.research.google.com/github/ArashDehghanyan/ml-practicres/blob/main/Customization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
print(tf.version.VERSION)

2.8.0


#Basics

In [3]:
print(tf.reduce_sum([1, 2, 3]).numpy())
print(tf.add(1, 2).numpy())
print(tf.add([1, 2], [3, 4]).numpy())
print(tf.square(5).numpy())
print((tf.square(2) + tf.square(3)).numpy())
x = tf.matmul([[1]], [[1, 2]])
print(x)
print(x.shape)
print(x.dtype)
print(x.numpy())

6
3
[4 6]
25
13
tf.Tensor([[1 2]], shape=(1, 2), dtype=int32)
(1, 2)
<dtype: 'int32'>
[[1 2]]


In [4]:
x = tf.random.uniform([3, 3])

print("Is there a GPU available:")
print(tf.config.list_physical_devices("GPU"))

print("Is the tensor on the GPU #0:")
print(x.device.endswith("GPU:0"))

Is there a GPU available:
[]
Is the tensor on the GPU #0:
False


In [5]:
print(x.device)

/job:localhost/replica:0/task:0/device:CPU:0


##Explicit device placement

In [6]:
import time

def time_matmul(x):
    start = time.time()
    for loop in range(10):
        tf.matmul(x, x)
    
    result = time.time() - start
    print("10 loops: {:0.2f}ms".format(1000 * result))

# Force execution on CPU
print("on CPU:")
with tf.device("CPU:0"):
    x = tf.random.uniform([1000, 1000])
    assert x.device.endswith("CPU:0")
    time_matmul(x)

# Force execution on GPU
print("on GPU:")
with tf.device("GPU:0"):
    x = tf.random.uniform([1000, 1000])
    assert x.device.endswith("GPU:0")
    time_matmul(x)
    

on CPU:
10 loops: 336.36ms
on GPU:


AssertionError: ignored

##Datasets

In [7]:
ds_tensor = tf.data.Dataset.from_tensor_slices([1,2,3,4,5,6,7,8])

import tempfile
_, filename = tempfile.mkstemp()

with open(filename, 'w') as f:
    f.write("""Line 1
    Line 2
    Line 3
    Lin3 4
    Line 5
    """)

ds_file = tf.data.TextLineDataset(filename)


##Apply transformations

In [8]:
ds_tensor = ds_tensor.map(tf.square).shuffle(2).batch(2)
ds_file = ds_file.shuffle(2).batch(2)

##Iterate

In [9]:
print("Elements of ds_tensor:")
for x in ds_tensor:
    print(x)


print("\n\nElements of ds_file:")
for x in ds_file:
    print(x)

Elements of ds_tensor:
tf.Tensor([1 9], shape=(2,), dtype=int32)
tf.Tensor([ 4 25], shape=(2,), dtype=int32)
tf.Tensor([16 36], shape=(2,), dtype=int32)
tf.Tensor([49 64], shape=(2,), dtype=int32)


Elements of ds_file:
tf.Tensor([b'Line 1' b'    Line 3'], shape=(2,), dtype=string)
tf.Tensor([b'    Lin3 4' b'    Line 5'], shape=(2,), dtype=string)
tf.Tensor([b'    Line 2' b'    '], shape=(2,), dtype=string)


#Layers

In [10]:
import numpy as np
import tensorflow as tf

print(tf.version.VERSION)
print(tf.config.list_physical_devices('GPU'))

2.8.0
[]


In [11]:
layer = tf.keras.layers.Dense(10, input_shape=(None, 5))

layer(tf.ones((10, 5))).shape

TensorShape([10, 10])

In [13]:
layer.variables

[<tf.Variable 'dense/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-1.5178511e-01,  1.1538720e-01,  1.7160177e-04,  6.2117976e-01,
          1.6247350e-01, -6.0888219e-01,  4.3196231e-01, -3.6160219e-01,
          1.5808946e-01, -5.7490534e-01],
        [-2.5809914e-01,  1.3711077e-01, -4.6136445e-01, -1.9767553e-01,
          1.6871029e-01,  4.2965025e-01,  3.4060645e-01,  4.6316880e-01,
          1.4357793e-01,  2.9037827e-01],
        [ 5.4126757e-01,  2.4239945e-01,  5.2429932e-01, -5.8878410e-01,
         -1.9878685e-02,  2.1762598e-01, -4.1061223e-02,  5.3282160e-01,
         -3.7681061e-01, -4.4200927e-01],
        [-5.5416536e-01,  3.4064698e-01,  5.8737952e-01,  9.7388506e-02,
          1.2719142e-01,  2.1635211e-01,  4.9411219e-01, -5.7243270e-01,
          3.6021358e-01,  3.4830934e-01],
        [ 1.8940729e-01, -4.5024157e-03,  1.5150964e-01, -1.4253721e-01,
          2.8681135e-01, -1.8239018e-01, -5.9461951e-01,  5.2161974e-01,
          2.7705348e-01,  5.6180161

In [14]:
layer.trainable_variables

[<tf.Variable 'dense/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-1.5178511e-01,  1.1538720e-01,  1.7160177e-04,  6.2117976e-01,
          1.6247350e-01, -6.0888219e-01,  4.3196231e-01, -3.6160219e-01,
          1.5808946e-01, -5.7490534e-01],
        [-2.5809914e-01,  1.3711077e-01, -4.6136445e-01, -1.9767553e-01,
          1.6871029e-01,  4.2965025e-01,  3.4060645e-01,  4.6316880e-01,
          1.4357793e-01,  2.9037827e-01],
        [ 5.4126757e-01,  2.4239945e-01,  5.2429932e-01, -5.8878410e-01,
         -1.9878685e-02,  2.1762598e-01, -4.1061223e-02,  5.3282160e-01,
         -3.7681061e-01, -4.4200927e-01],
        [-5.5416536e-01,  3.4064698e-01,  5.8737952e-01,  9.7388506e-02,
          1.2719142e-01,  2.1635211e-01,  4.9411219e-01, -5.7243270e-01,
          3.6021358e-01,  3.4830934e-01],
        [ 1.8940729e-01, -4.5024157e-03,  1.5150964e-01, -1.4253721e-01,
          2.8681135e-01, -1.8239018e-01, -5.9461951e-01,  5.2161974e-01,
          2.7705348e-01,  5.6180161

In [15]:
layer.kernel, layer.bias

(<tf.Variable 'dense/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-1.5178511e-01,  1.1538720e-01,  1.7160177e-04,  6.2117976e-01,
          1.6247350e-01, -6.0888219e-01,  4.3196231e-01, -3.6160219e-01,
          1.5808946e-01, -5.7490534e-01],
        [-2.5809914e-01,  1.3711077e-01, -4.6136445e-01, -1.9767553e-01,
          1.6871029e-01,  4.2965025e-01,  3.4060645e-01,  4.6316880e-01,
          1.4357793e-01,  2.9037827e-01],
        [ 5.4126757e-01,  2.4239945e-01,  5.2429932e-01, -5.8878410e-01,
         -1.9878685e-02,  2.1762598e-01, -4.1061223e-02,  5.3282160e-01,
         -3.7681061e-01, -4.4200927e-01],
        [-5.5416536e-01,  3.4064698e-01,  5.8737952e-01,  9.7388506e-02,
          1.2719142e-01,  2.1635211e-01,  4.9411219e-01, -5.7243270e-01,
          3.6021358e-01,  3.4830934e-01],
        [ 1.8940729e-01, -4.5024157e-03,  1.5150964e-01, -1.4253721e-01,
          2.8681135e-01, -1.8239018e-01, -5.9461951e-01,  5.2161974e-01,
          2.7705348e-01,  5.6180161

#Custom layers

In [16]:
class MyDenseLayer(tf.keras.layers.Layer):
    def __init__(self, num_outputs):
        super(MyDenseLayer, self).__init__()
        self.num_outputs = num_outputs

    def build(self, input_shape):
        self.kernel = self.add_weight(
            "kernel", shape=[int(input_shape[-1]), self.num_outputs]
        )

    def call(self, inputs):
        return tf.matmul(inputs, self.kernel)


In [17]:
layer = MyDenseLayer(10)
layer(tf.ones([10, 5])).shape

TensorShape([10, 10])

In [18]:
print([var.name for var in layer.trainable_variables])

['my_dense_layer/kernel:0']


##Residual Block

In [19]:
from tensorflow.keras import layers

In [20]:
class ResidualBlock(tf.keras.Model):
    def __init__(self, kernel_size, filters):
        super(ResidualBlock, self).__init__(name='')
        filter1, filter2, filter3 = filters

        self.conv2a = layers.Conv2D(filter1, (1, 1))
        self.bn2a = layers.BatchNormalization()

        self.conv2b = layers.Conv2D(filter2, kernel_size=kernel_size, padding='same')
        self.bn2b = layers.BatchNormalization()

        self.conv2c = layers.Conv2D(filter3, (1, 1))
        self.bn2c = layers.BatchNormalization()
    
    def call(self, input_tensor, training=False):
        x = tf.nn.relu(self.bn2a(self.conv2a(input_tensor), training=training))

        x = tf.nn.relu(self.bn2b(self.conv2b(x), training=training))

        x = self.bn2c(self.conv2c(x))

        x += input_tensor

        return tf.nn.relu(x)


In [21]:
block = ResidualBlock(1, [1, 2, 3])

_ = block(tf.zeros([1, 2, 3, 3]))

In [22]:
block.layers

In [23]:
len(block.variables)

18

In [24]:
block.summary()

Model: ""
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             multiple                  4         
                                                                 
 batch_normalization (BatchN  multiple                 4         
 ormalization)                                                   
                                                                 
 conv2d_1 (Conv2D)           multiple                  4         
                                                                 
 batch_normalization_1 (Batc  multiple                 8         
 hNormalization)                                                 
                                                                 
 conv2d_2 (Conv2D)           multiple                  9         
                                                                 
 batch_normalization_2 (Batc  multiple                 12        
