<a href="https://colab.research.google.com/github/ArashDehghanyan/ml-practicres/blob/main/Customization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
print(tf.version.VERSION)

2.8.0


#Basics

In [3]:
print(tf.reduce_sum([1, 2, 3]).numpy())
print(tf.add(1, 2).numpy())
print(tf.add([1, 2], [3, 4]).numpy())
print(tf.square(5).numpy())
print((tf.square(2) + tf.square(3)).numpy())
x = tf.matmul([[1]], [[1, 2]])
print(x)
print(x.shape)
print(x.dtype)
print(x.numpy())

6
3
[4 6]
25
13
tf.Tensor([[1 2]], shape=(1, 2), dtype=int32)
(1, 2)
<dtype: 'int32'>
[[1 2]]


In [4]:
x = tf.random.uniform([3, 3])

print("Is there a GPU available:")
print(tf.config.list_physical_devices("GPU"))

print("Is the tensor on the GPU #0:")
print(x.device.endswith("GPU:0"))

Is there a GPU available:
[]
Is the tensor on the GPU #0:
False


In [5]:
print(x.device)

/job:localhost/replica:0/task:0/device:CPU:0


##Explicit device placement

In [6]:
import time

def time_matmul(x):
    start = time.time()
    for loop in range(10):
        tf.matmul(x, x)
    
    result = time.time() - start
    print("10 loops: {:0.2f}ms".format(1000 * result))

# Force execution on CPU
print("on CPU:")
with tf.device("CPU:0"):
    x = tf.random.uniform([1000, 1000])
    assert x.device.endswith("CPU:0")
    time_matmul(x)

# Force execution on GPU
print("on GPU:")
with tf.device("GPU:0"):
    x = tf.random.uniform([1000, 1000])
    assert x.device.endswith("GPU:0")
    time_matmul(x)
    

on CPU:
10 loops: 336.36ms
on GPU:


AssertionError: ignored

##Datasets

In [7]:
ds_tensor = tf.data.Dataset.from_tensor_slices([1,2,3,4,5,6,7,8])

import tempfile
_, filename = tempfile.mkstemp()

with open(filename, 'w') as f:
    f.write("""Line 1
    Line 2
    Line 3
    Lin3 4
    Line 5
    """)

ds_file = tf.data.TextLineDataset(filename)


##Apply transformations

In [8]:
ds_tensor = ds_tensor.map(tf.square).shuffle(2).batch(2)
ds_file = ds_file.shuffle(2).batch(2)

##Iterate

In [9]:
print("Elements of ds_tensor:")
for x in ds_tensor:
    print(x)


print("\n\nElements of ds_file:")
for x in ds_file:
    print(x)

Elements of ds_tensor:
tf.Tensor([1 9], shape=(2,), dtype=int32)
tf.Tensor([ 4 25], shape=(2,), dtype=int32)
tf.Tensor([16 36], shape=(2,), dtype=int32)
tf.Tensor([49 64], shape=(2,), dtype=int32)


Elements of ds_file:
tf.Tensor([b'Line 1' b'    Line 3'], shape=(2,), dtype=string)
tf.Tensor([b'    Lin3 4' b'    Line 5'], shape=(2,), dtype=string)
tf.Tensor([b'    Line 2' b'    '], shape=(2,), dtype=string)


#Layers

In [1]:
import numpy as np
import tensorflow as tf

print(tf.version.VERSION)
print(tf.config.list_physical_devices('GPU'))

2.8.0
[]


In [2]:
layer = tf.keras.layers.Dense(10, input_shape=(None, 5))

layer(tf.ones((10, 5))).shape

TensorShape([10, 10])

In [3]:
layer.variables

[<tf.Variable 'dense/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.41724172, -0.09226394,  0.3397836 , -0.3991214 ,  0.20124394,
          0.51783615, -0.39522213,  0.13868213,  0.08162898,  0.00265944],
        [ 0.37605828,  0.58732635,  0.43068832,  0.16144407,  0.55269784,
         -0.0653258 ,  0.37946814,  0.36646664,  0.19084209, -0.21140382],
        [ 0.28349084,  0.44152027, -0.48583692,  0.4543714 ,  0.09701622,
         -0.05751777,  0.6202561 , -0.30055806, -0.01326418, -0.17479658],
        [ 0.22828871, -0.624149  , -0.5066743 , -0.620874  , -0.43883413,
         -0.56412286,  0.09175503,  0.09648168,  0.5658563 , -0.25477183],
        [ 0.44596297,  0.63171715,  0.5291566 , -0.62831366,  0.15750802,
          0.34291607, -0.48402172,  0.03734773,  0.22853982, -0.626126  ]],
       dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [4]:
layer.trainable_variables

[<tf.Variable 'dense/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.41724172, -0.09226394,  0.3397836 , -0.3991214 ,  0.20124394,
          0.51783615, -0.39522213,  0.13868213,  0.08162898,  0.00265944],
        [ 0.37605828,  0.58732635,  0.43068832,  0.16144407,  0.55269784,
         -0.0653258 ,  0.37946814,  0.36646664,  0.19084209, -0.21140382],
        [ 0.28349084,  0.44152027, -0.48583692,  0.4543714 ,  0.09701622,
         -0.05751777,  0.6202561 , -0.30055806, -0.01326418, -0.17479658],
        [ 0.22828871, -0.624149  , -0.5066743 , -0.620874  , -0.43883413,
         -0.56412286,  0.09175503,  0.09648168,  0.5658563 , -0.25477183],
        [ 0.44596297,  0.63171715,  0.5291566 , -0.62831366,  0.15750802,
          0.34291607, -0.48402172,  0.03734773,  0.22853982, -0.626126  ]],
       dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [5]:
layer.kernel, layer.bias

(<tf.Variable 'dense/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.41724172, -0.09226394,  0.3397836 , -0.3991214 ,  0.20124394,
          0.51783615, -0.39522213,  0.13868213,  0.08162898,  0.00265944],
        [ 0.37605828,  0.58732635,  0.43068832,  0.16144407,  0.55269784,
         -0.0653258 ,  0.37946814,  0.36646664,  0.19084209, -0.21140382],
        [ 0.28349084,  0.44152027, -0.48583692,  0.4543714 ,  0.09701622,
         -0.05751777,  0.6202561 , -0.30055806, -0.01326418, -0.17479658],
        [ 0.22828871, -0.624149  , -0.5066743 , -0.620874  , -0.43883413,
         -0.56412286,  0.09175503,  0.09648168,  0.5658563 , -0.25477183],
        [ 0.44596297,  0.63171715,  0.5291566 , -0.62831366,  0.15750802,
          0.34291607, -0.48402172,  0.03734773,  0.22853982, -0.626126  ]],
       dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>)

#Custom layers

In [6]:
class MyDenseLayer(tf.keras.layers.Layer):
    def __init__(self, num_outputs):
        super(MyDenseLayer, self).__init__()
        self.num_outputs = num_outputs

    def build(self, input_shape):
        self.kernel = self.add_weight(
            "kernel", shape=[int(input_shape[-1]), self.num_outputs]
        )

    def call(self, inputs):
        return tf.matmul(inputs, self.kernel)


In [7]:
layer = MyDenseLayer(10)
layer(tf.ones([10, 5])).shape

TensorShape([10, 10])

In [8]:
print([var.name for var in layer.trainable_variables])

['my_dense_layer/kernel:0']


##Residual Block

In [9]:
from tensorflow.keras import layers

In [10]:
class ResidualBlock(tf.keras.Model):
    def __init__(self, kernel_size, filters):
        super(ResidualBlock, self).__init__(name='')
        filter1, filter2, filter3 = filters

        self.conv2a = layers.Conv2D(filter1, (1, 1))
        self.bn2a = layers.BatchNormalization()

        self.conv2b = layers.Conv2D(filter2, kernel_size=kernel_size, padding='same')
        self.bn2b = layers.BatchNormalization()

        self.conv2c = layers.Conv2D(filter3, (1, 1))
        self.bn2c = layers.BatchNormalization()
    
    def call(self, input_tensor, training=False):
        x = tf.nn.relu(self.bn2a(self.conv2a(input_tensor), training=training))

        x = tf.nn.relu(self.bn2b(self.conv2b(x), training=training))

        x = self.bn2c(self.conv2c(x))

        x += input_tensor

        return tf.nn.relu(x)


In [11]:
block = ResidualBlock(1, [1, 2, 3])

_ = block(tf.zeros([1, 2, 3, 3]))

In [12]:
block.layers

In [13]:
len(block.variables)

18

In [14]:
block.summary()

Model: ""
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             multiple                  4         
                                                                 
 batch_normalization (BatchN  multiple                 4         
 ormalization)                                                   
                                                                 
 conv2d_1 (Conv2D)           multiple                  4         
                                                                 
 batch_normalization_1 (Batc  multiple                 8         
 hNormalization)                                                 
                                                                 
 conv2d_2 (Conv2D)           multiple                  9         
                                                                 
 batch_normalization_2 (Batc  multiple                 12        


##Install tfds-nightly dataset

In [1]:
! pip install -q tfds-nightly 

In [2]:
import os
import tensorflow as tf
import tensorflow_datasets as tfds
import matplotlib.pyplot as plt

print("Tensorflow version: {}".format(tf.__version__))
print("Tensorflow dataset version: {}".format(tfds.__version__))

Tensorflow version: 2.8.0
Tensorflow dataset version: 4.5.2+nightly


##Import dataset
###Preview the data

In [4]:
ds_preview, info = tfds.load('penguins/simple', split='train', with_info=True)
df = tfds.as_dataframe(ds_preview.take(5), info)
print(df)
print(info.features)

   body_mass_g  culmen_depth_mm  culmen_length_mm  flipper_length_mm  island  \
0       4200.0             13.9         45.500000              210.0       0   
1       4650.0             13.7         40.900002              214.0       0   
2       5300.0             14.2         51.299999              218.0       0   
3       5650.0             15.0         47.799999              215.0       0   
4       5050.0             15.8         46.299999              215.0       0   

   sex  species  
0    0        2  
1    0        2  
2    1        2  
3    1        2  
4    1        2  
FeaturesDict({
    'body_mass_g': tf.float32,
    'culmen_depth_mm': tf.float32,
    'culmen_length_mm': tf.float32,
    'flipper_length_mm': tf.float32,
    'island': ClassLabel(shape=(), dtype=tf.int64, num_classes=3),
    'sex': ClassLabel(shape=(), dtype=tf.int64, num_classes=3),
    'species': ClassLabel(shape=(), dtype=tf.int64, num_classes=3),
})


In [5]:
dataset_split, info = tfds.load('penguins/processed', split=['train[:20%]', 'train[20%:]'], as_supervised=True, with_info=True)
ds_test = dataset_split[0]
ds_train = dataset_split[1]
assert isinstance(ds_test, tf.data.Dataset)

print(info.features)
df_test = tfds.as_dataframe(ds_test.take(5), info)
print("Test dataset sample:")
print(df_test)

df_train = tfds.as_dataframe(ds_train.take(5), info)
print("Train dataset sample:")
print(df_train)

ds_train_batch = ds_train.batch(32)

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Generating splits...:   0%|          | 0/1 [00:00<?, ? splits/s]

Generating train examples...:   0%|          | 0/334 [00:00<?, ? examples/s]

Shuffling ~/tensorflow_datasets/penguins/processed/1.0.0.incompleteX3IE7V/penguins-train.tfrecord*...:   0%|  …

Dataset penguins downloaded and prepared to ~/tensorflow_datasets/penguins/processed/1.0.0. Subsequent calls will reuse this data.
FeaturesDict({
    'features': Tensor(shape=(4,), dtype=tf.float32),
    'species': ClassLabel(shape=(), dtype=tf.int64, num_classes=3),
})
Test dataset sample:
                                         features  species
0  [0.6545454, 0.22619048, 0.89830506, 0.6388889]        2
1        [0.36, 0.04761905, 0.6440678, 0.4027778]        2
2       [0.68, 0.30952382, 0.91525424, 0.6944444]        2
3   [0.6181818, 0.20238096, 0.8135593, 0.6805556]        2
4  [0.5527273, 0.26190478, 0.84745765, 0.7083333]        2
Train dataset sample:
                                         features  species
0  [0.49818182, 0.6904762, 0.42372882, 0.4027778]        0
1      [0.48, 0.071428575, 0.6440678, 0.44444445]        2
2    [0.7236364, 0.9047619, 0.6440678, 0.5833333]        1
3  [0.34545454, 0.5833333, 0.33898306, 0.3472222]        0
4       [0.10909091, 0.75, 0.3559322,

In [6]:
features, labels = next(iter(ds_train_batch))

print(features)
print(labels)

tf.Tensor(
[[0.49818182 0.6904762  0.42372882 0.4027778 ]
 [0.48       0.07142857 0.6440678  0.44444445]
 [0.7236364  0.9047619  0.6440678  0.5833333 ]
 [0.34545454 0.5833333  0.33898306 0.3472222 ]
 [0.10909091 0.75       0.3559322  0.41666666]
 [0.6690909  0.63095236 0.47457626 0.19444445]
 [0.8036364  0.9166667  0.4915254  0.44444445]
 [0.4909091  0.75       0.37288135 0.22916667]
 [0.33454546 0.85714287 0.37288135 0.2361111 ]
 [0.32       0.41666666 0.2542373  0.1388889 ]
 [0.41454545 0.5952381  0.5084746  0.19444445]
 [0.14909092 0.48809522 0.2542373  0.125     ]
 [0.23636363 0.4642857  0.27118644 0.05555556]
 [0.22181818 0.5952381  0.22033899 0.3472222 ]
 [0.24727273 0.5595238  0.15254237 0.25694445]
 [0.63272727 0.35714287 0.88135594 0.8194444 ]
 [0.47272727 0.15476191 0.6440678  0.4722222 ]
 [0.6036364  0.23809524 0.84745765 0.7361111 ]
 [0.26909092 0.5595238  0.27118644 0.16666667]
 [0.28       0.71428573 0.20338982 0.5416667 ]
 [0.10545454 0.5714286  0.33898306 0.2847222 ]
 [