<a href="https://colab.research.google.com/github/ArashDehghanyan/ml-practicres/blob/main/Customization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
print(tf.version.VERSION)

2.8.0


#Basics

In [3]:
print(tf.reduce_sum([1, 2, 3]).numpy())
print(tf.add(1, 2).numpy())
print(tf.add([1, 2], [3, 4]).numpy())
print(tf.square(5).numpy())
print((tf.square(2) + tf.square(3)).numpy())
x = tf.matmul([[1]], [[1, 2]])
print(x)
print(x.shape)
print(x.dtype)
print(x.numpy())

6
3
[4 6]
25
13
tf.Tensor([[1 2]], shape=(1, 2), dtype=int32)
(1, 2)
<dtype: 'int32'>
[[1 2]]


In [4]:
x = tf.random.uniform([3, 3])

print("Is there a GPU available:")
print(tf.config.list_physical_devices("GPU"))

print("Is the tensor on the GPU #0:")
print(x.device.endswith("GPU:0"))

Is there a GPU available:
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
Is the tensor on the GPU #0:
True


In [5]:
print(x.device)

/job:localhost/replica:0/task:0/device:GPU:0


##Explicit device placement

In [6]:
import time

def time_matmul(x):
    start = time.time()
    for loop in range(10):
        tf.matmul(x, x)
    
    result = time.time() - start
    print("10 loops: {:0.2f}ms".format(1000 * result))

# Force execution on CPU
print("on CPU:")
with tf.device("CPU:0"):
    x = tf.random.uniform([1000, 1000])
    assert x.device.endswith("CPU:0")
    time_matmul(x)

# Force execution on GPU
print("on GPU:")
with tf.device("GPU:0"):
    x = tf.random.uniform([1000, 1000])
    assert x.device.endswith("GPU:0")
    time_matmul(x)
    

on CPU:
10 loops: 445.63ms
on GPU:
10 loops: 1283.01ms


##Datasets

In [7]:
ds_tensor = tf.data.Dataset.from_tensor_slices([1,2,3,4,5,6,7,8])

import tempfile
_, filename = tempfile.mkstemp()

with open(filename, 'w') as f:
    f.write("""Line 1
    Line 2
    Line 3
    Lin3 4
    Line 5
    """)

ds_file = tf.data.TextLineDataset(filename)


##Apply transformations

In [8]:
ds_tensor = ds_tensor.map(tf.square).shuffle(2).batch(2)
ds_file = ds_file.shuffle(2).batch(2)

##Iterate

In [9]:
print("Elements of ds_tensor:")
for x in ds_tensor:
    print(x)


print("\n\nElements of ds_file:")
for x in ds_file:
    print(x)

Elements of ds_tensor:
tf.Tensor([1 9], shape=(2,), dtype=int32)
tf.Tensor([ 4 25], shape=(2,), dtype=int32)
tf.Tensor([36 49], shape=(2,), dtype=int32)
tf.Tensor([16 64], shape=(2,), dtype=int32)


Elements of ds_file:
tf.Tensor([b'Line 1' b'    Line 3'], shape=(2,), dtype=string)
tf.Tensor([b'    Lin3 4' b'    Line 5'], shape=(2,), dtype=string)
tf.Tensor([b'    Line 2' b'    '], shape=(2,), dtype=string)


#Layers

In [10]:
import numpy as np
import tensorflow as tf

print(tf.version.VERSION)
print(tf.config.list_physical_devices('GPU'))

2.8.0
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [11]:
layer = tf.keras.layers.Dense(10, input_shape=(None, 5))

layer(tf.ones((10, 5))).shape

TensorShape([10, 10])

In [12]:
layer.variables

[<tf.Variable 'dense/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.21179754,  0.21092278, -0.40015218, -0.22113153, -0.23944607,
         -0.40425682, -0.15561366,  0.60537654,  0.32219583, -0.26386443],
        [-0.48199585,  0.25304425, -0.46911347,  0.45276457,  0.6172239 ,
         -0.25503737,  0.02143198,  0.581798  ,  0.18439204, -0.50854516],
        [-0.51820004,  0.4374779 , -0.3796827 ,  0.60323566, -0.22683   ,
          0.16394353,  0.43335027, -0.5503243 ,  0.3695169 , -0.1428121 ],
        [-0.2173799 ,  0.53955716,  0.27413273,  0.44992357,  0.1720857 ,
          0.11956406,  0.50344497, -0.4318034 , -0.21277991, -0.5778047 ],
        [ 0.07842165, -0.58695203,  0.38537103, -0.16278383, -0.09324139,
          0.10304582, -0.60329   ,  0.40765303,  0.09181327, -0.3044617 ]],
       dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [13]:
layer.trainable_variables

[<tf.Variable 'dense/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.21179754,  0.21092278, -0.40015218, -0.22113153, -0.23944607,
         -0.40425682, -0.15561366,  0.60537654,  0.32219583, -0.26386443],
        [-0.48199585,  0.25304425, -0.46911347,  0.45276457,  0.6172239 ,
         -0.25503737,  0.02143198,  0.581798  ,  0.18439204, -0.50854516],
        [-0.51820004,  0.4374779 , -0.3796827 ,  0.60323566, -0.22683   ,
          0.16394353,  0.43335027, -0.5503243 ,  0.3695169 , -0.1428121 ],
        [-0.2173799 ,  0.53955716,  0.27413273,  0.44992357,  0.1720857 ,
          0.11956406,  0.50344497, -0.4318034 , -0.21277991, -0.5778047 ],
        [ 0.07842165, -0.58695203,  0.38537103, -0.16278383, -0.09324139,
          0.10304582, -0.60329   ,  0.40765303,  0.09181327, -0.3044617 ]],
       dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [14]:
layer.kernel, layer.bias

(<tf.Variable 'dense/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.21179754,  0.21092278, -0.40015218, -0.22113153, -0.23944607,
         -0.40425682, -0.15561366,  0.60537654,  0.32219583, -0.26386443],
        [-0.48199585,  0.25304425, -0.46911347,  0.45276457,  0.6172239 ,
         -0.25503737,  0.02143198,  0.581798  ,  0.18439204, -0.50854516],
        [-0.51820004,  0.4374779 , -0.3796827 ,  0.60323566, -0.22683   ,
          0.16394353,  0.43335027, -0.5503243 ,  0.3695169 , -0.1428121 ],
        [-0.2173799 ,  0.53955716,  0.27413273,  0.44992357,  0.1720857 ,
          0.11956406,  0.50344497, -0.4318034 , -0.21277991, -0.5778047 ],
        [ 0.07842165, -0.58695203,  0.38537103, -0.16278383, -0.09324139,
          0.10304582, -0.60329   ,  0.40765303,  0.09181327, -0.3044617 ]],
       dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>)

#Custom layers

In [22]:
class MyDenseLayer(tf.keras.layers.Layer):
    def __init__(self, num_outputs):
        super(MyDenseLayer, self).__init__()
        self.num_outputs = num_outputs

    def build(self, input_shape):
        self.kernel = self.add_weight(
            "kernel", shape=[int(input_shape[-1]), self.num_outputs]
        )

    def call(self, inputs):
        return tf.matmul(inputs, self.kernel)


In [26]:
layer = MyDenseLayer(10)
layer(tf.ones([10, 5])).shape

TensorShape([10, 10])

In [27]:
print([var.name for var in layer.trainable_variables])

['my_dense_layer_6/kernel:0']
